## Numerical operations on arrays
### Elementwise operations
#### Basic operations


- With scalars:

In [2]:
import numpy as np
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [3]:
2 ** a

array([ 2,  4,  8, 16])

- All arithmetic operates elementwise:

In [6]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [7]:
a - b

array([-1.,  0.,  1.,  2.])

In [8]:
a * b

array([2., 4., 6., 8.])

In [13]:
c = np.arange(5)
2 ** (c + 1) - c

array([ 2,  3,  6, 13, 28])

* These operations are of course much faster than if you did them in pure python:

In [16]:
a = np.arange(10000)
%timeit a + 1

5.67 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
l = range(10000)
%timeit [x+1 for x in l]

636 µs ± 21.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



#### Other operations


- Comparisons:

In [19]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [20]:
a > b

array([False, False,  True, False])

- Array-wise comparisons:

In [22]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [23]:
np.array_equal(a,c)

True

- Logical operations:

In [25]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

a

array([ True,  True, False, False])

In [26]:
b

array([ True, False,  True, False])

In [27]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [29]:
np.logical_and(a,b)

array([ True, False, False, False])

- Transcendental functions:

In [33]:
a = np.arange(5)

In [34]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [37]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [38]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

- Shape mismatches

In [39]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

- Transposition

In [40]:
a = np.triu(np.ones((3,3)),1)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])


### Basic reductions
