## More elaborate arrays
### More data types

#### Casting

- “Bigger” type wins in mixed-type operations:

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]) + 1.5
a, b

(array([1, 2, 3]), array([2.5, 3.5, 4.5]))

In [4]:
a.dtype, b.dtype

(dtype('int64'), dtype('float64'))

- Assignment never changes the type!

In [7]:
a = np.array([1,2,3])
a[1] = 2
a

array([1, 2, 3])

- Forced casts:

In [8]:
a = np.array([1,2,3])
b = a.astype(float)
b

array([1., 2., 3.])

#### Different data type sizes

### Structured data types
### maskedarray: dealing with (propagation of) missing data